<?php

/**
 * Created by PhpStorm.
 * User: LYC
 * Date: 2018/4/15
 * Time: 17:22
 */
namespace  app\common\controller;

use think\Controller;
use think\Db;
use think\Request;
use think\Response;

class BaseController extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    /*
     * 验证是否登录
     * */
    public function checkLogin(){
        $input=Request::instance()->param();
        $token_server=Db::table('user_token')->where('user_id','=',$input['user_id'])->find();
        if(empty($input['user_token']) || empty($input['user_id']) || $input['user_token'] != $token_server['user_token']){
            $jsonMsg=json_encode(['code'=>'100','msg'=>'Unauthorized']);
            die($jsonMsg);
        }else if ($input['user_token'] == $token_server['user_token'] && strtotime(time()) - strtotime($token_server['time_out']) > 0){
            $jsonMsg=json_encode(['code'=>'100','msg'=>'token timeOut']);
            die($jsonMsg);
        }
    }
}